/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedBibliaRouteImport } from './routes/_authenticated/biblia'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDevocionalRouteImport } from './routes/_authenticated/devocional'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedEscolaRouteImport } from './routes/_authenticated/escola'
import { Route as AuthenticatedEstudosRouteImport } from './routes/_authenticated/estudos'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedTrilhasRouteImport } from './routes/_authenticated/trilhas'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAssistenteIndexRouteImport } from './routes/_authenticated/assistente.index'
import { Route as AuthenticatedAssistenteThreadIdRouteImport } from './routes/_authenticated/assistente.$threadId'
import { Route as AuthenticatedEscolaIndexRouteImport } from './routes/_authenticated/escola.index'
import { Route as AuthenticatedEscolaSlugRouteImport } from './routes/_authenticated/escola.$slug'
import { Route as AuthenticatedEstudosIndexRouteImport } from './routes/_authenticated/estudos.index'
import { Route as AuthenticatedEstudosSlugRouteImport } from './routes/_authenticated/estudos.$slug'
import { Route as AuthenticatedPlanosIndexRouteImport } from './routes/_authenticated/planos.index'
import { Route as AuthenticatedPlanosSlugRouteImport } from './routes/_authenticated/planos.$slug'
import { Route as AuthenticatedTrilhasIndexRouteImport } from './routes/_authenticated/trilhas.index'
import { Route as AuthenticatedTrilhasSlugRouteImport } from './routes/_authenticated/trilhas.$slug'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin.cursos.index'
import { Route as AuthenticatedAdminCursosIdRouteImport } from './routes/_authenticated/admin.cursos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliaRoute = AuthenticatedBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevocionalRoute = AuthenticatedDevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscolaRoute = AuthenticatedEscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudosRoute = AuthenticatedEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrilhasRoute = AuthenticatedTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAssistenteIndexRoute =
  AuthenticatedAssistenteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistenteRoute,
  } as any)
const AuthenticatedAssistenteThreadIdRoute =
  AuthenticatedAssistenteThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistenteRoute,
  } as any)
const AuthenticatedEscolaIndexRoute =
  AuthenticatedEscolaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEscolaRoute,
  } as any)
const AuthenticatedEscolaSlugRoute = AuthenticatedEscolaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedEscolaRoute,
} as any)
const AuthenticatedEstudosIndexRoute =
  AuthenticatedEstudosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstudosRoute,
  } as any)
const AuthenticatedEstudosSlugRoute =
  AuthenticatedEstudosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedEstudosRoute,
  } as any)
const AuthenticatedPlanosIndexRoute =
  AuthenticatedPlanosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlanosRoute,
  } as any)
const AuthenticatedPlanosSlugRoute = AuthenticatedPlanosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedPlanosRoute,
} as any)
const AuthenticatedTrilhasIndexRoute =
  AuthenticatedTrilhasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrilhasRoute,
  } as any)
const AuthenticatedTrilhasSlugRoute =
  AuthenticatedTrilhasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedTrilhasRoute,
  } as any)
const AuthenticatedAdminCursosIndexRoute =
  AuthenticatedAdminCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCursosIdRoute =
  AuthenticatedAdminCursosIdRouteImport.update({
    id: '/cursos/$id',
    path: '/cursos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assistente': typeof AuthenticatedAssistenteRouteWithChildren
  '/biblia': typeof AuthenticatedBibliaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/escola': typeof AuthenticatedEscolaRouteWithChildren
  '/estudos': typeof AuthenticatedEstudosRouteWithChildren
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/planos': typeof AuthenticatedPlanosRouteWithChildren
  '/trilhas': typeof AuthenticatedTrilhasRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/escola/$slug': typeof AuthenticatedEscolaSlugRoute
  '/estudos/$slug': typeof AuthenticatedEstudosSlugRoute
  '/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/trilhas/$slug': typeof AuthenticatedTrilhasSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/escola/': typeof AuthenticatedEscolaIndexRoute
  '/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/planos/': typeof AuthenticatedPlanosIndexRoute
  '/trilhas/': typeof AuthenticatedTrilhasIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/api/chat': typeof ApiChatRoute
  '/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/escola/$slug': typeof AuthenticatedEscolaSlugRoute
  '/estudos/$slug': typeof AuthenticatedEstudosSlugRoute
  '/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/trilhas/$slug': typeof AuthenticatedTrilhasSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/assistente': typeof AuthenticatedAssistenteIndexRoute
  '/escola': typeof AuthenticatedEscolaIndexRoute
  '/estudos': typeof AuthenticatedEstudosIndexRoute
  '/planos': typeof AuthenticatedPlanosIndexRoute
  '/trilhas': typeof AuthenticatedTrilhasIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRouteWithChildren
  '/_authenticated/biblia': typeof AuthenticatedBibliaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/devocional': typeof AuthenticatedDevocionalRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/escola': typeof AuthenticatedEscolaRouteWithChildren
  '/_authenticated/estudos': typeof AuthenticatedEstudosRouteWithChildren
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRouteWithChildren
  '/_authenticated/trilhas': typeof AuthenticatedTrilhasRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/_authenticated/escola/$slug': typeof AuthenticatedEscolaSlugRoute
  '/_authenticated/estudos/$slug': typeof AuthenticatedEstudosSlugRoute
  '/_authenticated/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/_authenticated/trilhas/$slug': typeof AuthenticatedTrilhasSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/_authenticated/escola/': typeof AuthenticatedEscolaIndexRoute
  '/_authenticated/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/_authenticated/planos/': typeof AuthenticatedPlanosIndexRoute
  '/_authenticated/trilhas/': typeof AuthenticatedTrilhasIndexRoute
  '/_authenticated/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/admin'
    | '/assistente'
    | '/biblia'
    | '/configuracoes'
    | '/devocional'
    | '/diario'
    | '/escola'
    | '/estudos'
    | '/favoritos'
    | '/inicio'
    | '/metas'
    | '/onboarding'
    | '/pesquisa'
    | '/planos'
    | '/trilhas'
    | '/api/chat'
    | '/assistente/$threadId'
    | '/escola/$slug'
    | '/estudos/$slug'
    | '/planos/$slug'
    | '/trilhas/$slug'
    | '/admin/'
    | '/assistente/'
    | '/escola/'
    | '/estudos/'
    | '/planos/'
    | '/trilhas/'
    | '/admin/cursos/$id'
    | '/admin/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/biblia'
    | '/configuracoes'
    | '/devocional'
    | '/diario'
    | '/favoritos'
    | '/inicio'
    | '/metas'
    | '/onboarding'
    | '/pesquisa'
    | '/api/chat'
    | '/assistente/$threadId'
    | '/escola/$slug'
    | '/estudos/$slug'
    | '/planos/$slug'
    | '/trilhas/$slug'
    | '/admin'
    | '/assistente'
    | '/escola'
    | '/estudos'
    | '/planos'
    | '/trilhas'
    | '/admin/cursos/$id'
    | '/admin/cursos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assistente'
    | '/_authenticated/biblia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/devocional'
    | '/_authenticated/diario'
    | '/_authenticated/escola'
    | '/_authenticated/estudos'
    | '/_authenticated/favoritos'
    | '/_authenticated/inicio'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/pesquisa'
    | '/_authenticated/planos'
    | '/_authenticated/trilhas'
    | '/api/chat'
    | '/_authenticated/assistente/$threadId'
    | '/_authenticated/escola/$slug'
    | '/_authenticated/estudos/$slug'
    | '/_authenticated/planos/$slug'
    | '/_authenticated/trilhas/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/assistente/'
    | '/_authenticated/escola/'
    | '/_authenticated/estudos/'
    | '/_authenticated/planos/'
    | '/_authenticated/trilhas/'
    | '/_authenticated/admin/cursos/$id'
    | '/_authenticated/admin/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia': {
      id: '/_authenticated/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof AuthenticatedBibliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devocional': {
      id: '/_authenticated/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof AuthenticatedDevocionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escola': {
      id: '/_authenticated/escola'
      path: '/escola'
      fullPath: '/escola'
      preLoaderRoute: typeof AuthenticatedEscolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos': {
      id: '/_authenticated/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AuthenticatedEstudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trilhas': {
      id: '/_authenticated/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof AuthenticatedTrilhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/assistente/': {
      id: '/_authenticated/assistente/'
      path: '/'
      fullPath: '/assistente/'
      preLoaderRoute: typeof AuthenticatedAssistenteIndexRouteImport
      parentRoute: typeof AuthenticatedAssistenteRoute
    }
    '/_authenticated/assistente/$threadId': {
      id: '/_authenticated/assistente/$threadId'
      path: '/$threadId'
      fullPath: '/assistente/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistenteThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistenteRoute
    }
    '/_authenticated/escola/': {
      id: '/_authenticated/escola/'
      path: '/'
      fullPath: '/escola/'
      preLoaderRoute: typeof AuthenticatedEscolaIndexRouteImport
      parentRoute: typeof AuthenticatedEscolaRoute
    }
    '/_authenticated/escola/$slug': {
      id: '/_authenticated/escola/$slug'
      path: '/$slug'
      fullPath: '/escola/$slug'
      preLoaderRoute: typeof AuthenticatedEscolaSlugRouteImport
      parentRoute: typeof AuthenticatedEscolaRoute
    }
    '/_authenticated/estudos/': {
      id: '/_authenticated/estudos/'
      path: '/'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AuthenticatedEstudosIndexRouteImport
      parentRoute: typeof AuthenticatedEstudosRoute
    }
    '/_authenticated/estudos/$slug': {
      id: '/_authenticated/estudos/$slug'
      path: '/$slug'
      fullPath: '/estudos/$slug'
      preLoaderRoute: typeof AuthenticatedEstudosSlugRouteImport
      parentRoute: typeof AuthenticatedEstudosRoute
    }
    '/_authenticated/planos/': {
      id: '/_authenticated/planos/'
      path: '/'
      fullPath: '/planos/'
      preLoaderRoute: typeof AuthenticatedPlanosIndexRouteImport
      parentRoute: typeof AuthenticatedPlanosRoute
    }
    '/_authenticated/planos/$slug': {
      id: '/_authenticated/planos/$slug'
      path: '/$slug'
      fullPath: '/planos/$slug'
      preLoaderRoute: typeof AuthenticatedPlanosSlugRouteImport
      parentRoute: typeof AuthenticatedPlanosRoute
    }
    '/_authenticated/trilhas/': {
      id: '/_authenticated/trilhas/'
      path: '/'
      fullPath: '/trilhas/'
      preLoaderRoute: typeof AuthenticatedTrilhasIndexRouteImport
      parentRoute: typeof AuthenticatedTrilhasRoute
    }
    '/_authenticated/trilhas/$slug': {
      id: '/_authenticated/trilhas/$slug'
      path: '/$slug'
      fullPath: '/trilhas/$slug'
      preLoaderRoute: typeof AuthenticatedTrilhasSlugRouteImport
      parentRoute: typeof AuthenticatedTrilhasRoute
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cursos/$id': {
      id: '/_authenticated/admin/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AuthenticatedAdminCursosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCursosIdRoute: typeof AuthenticatedAdminCursosIdRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCursosIdRoute: AuthenticatedAdminCursosIdRoute,
  AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAssistenteRouteChildren {
  AuthenticatedAssistenteThreadIdRoute: typeof AuthenticatedAssistenteThreadIdRoute
  AuthenticatedAssistenteIndexRoute: typeof AuthenticatedAssistenteIndexRoute
}

const AuthenticatedAssistenteRouteChildren: AuthenticatedAssistenteRouteChildren =
  {
    AuthenticatedAssistenteThreadIdRoute: AuthenticatedAssistenteThreadIdRoute,
    AuthenticatedAssistenteIndexRoute: AuthenticatedAssistenteIndexRoute,
  }

const AuthenticatedAssistenteRouteWithChildren =
  AuthenticatedAssistenteRoute._addFileChildren(
    AuthenticatedAssistenteRouteChildren,
  )

interface AuthenticatedEscolaRouteChildren {
  AuthenticatedEscolaSlugRoute: typeof AuthenticatedEscolaSlugRoute
  AuthenticatedEscolaIndexRoute: typeof AuthenticatedEscolaIndexRoute
}

const AuthenticatedEscolaRouteChildren: AuthenticatedEscolaRouteChildren = {
  AuthenticatedEscolaSlugRoute: AuthenticatedEscolaSlugRoute,
  AuthenticatedEscolaIndexRoute: AuthenticatedEscolaIndexRoute,
}

const AuthenticatedEscolaRouteWithChildren =
  AuthenticatedEscolaRoute._addFileChildren(AuthenticatedEscolaRouteChildren)

interface AuthenticatedEstudosRouteChildren {
  AuthenticatedEstudosSlugRoute: typeof AuthenticatedEstudosSlugRoute
  AuthenticatedEstudosIndexRoute: typeof AuthenticatedEstudosIndexRoute
}

const AuthenticatedEstudosRouteChildren: AuthenticatedEstudosRouteChildren = {
  AuthenticatedEstudosSlugRoute: AuthenticatedEstudosSlugRoute,
  AuthenticatedEstudosIndexRoute: AuthenticatedEstudosIndexRoute,
}

const AuthenticatedEstudosRouteWithChildren =
  AuthenticatedEstudosRoute._addFileChildren(AuthenticatedEstudosRouteChildren)

interface AuthenticatedPlanosRouteChildren {
  AuthenticatedPlanosSlugRoute: typeof AuthenticatedPlanosSlugRoute
  AuthenticatedPlanosIndexRoute: typeof AuthenticatedPlanosIndexRoute
}

const AuthenticatedPlanosRouteChildren: AuthenticatedPlanosRouteChildren = {
  AuthenticatedPlanosSlugRoute: AuthenticatedPlanosSlugRoute,
  AuthenticatedPlanosIndexRoute: AuthenticatedPlanosIndexRoute,
}

const AuthenticatedPlanosRouteWithChildren =
  AuthenticatedPlanosRoute._addFileChildren(AuthenticatedPlanosRouteChildren)

interface AuthenticatedTrilhasRouteChildren {
  AuthenticatedTrilhasSlugRoute: typeof AuthenticatedTrilhasSlugRoute
  AuthenticatedTrilhasIndexRoute: typeof AuthenticatedTrilhasIndexRoute
}

const AuthenticatedTrilhasRouteChildren: AuthenticatedTrilhasRouteChildren = {
  AuthenticatedTrilhasSlugRoute: AuthenticatedTrilhasSlugRoute,
  AuthenticatedTrilhasIndexRoute: AuthenticatedTrilhasIndexRoute,
}

const AuthenticatedTrilhasRouteWithChildren =
  AuthenticatedTrilhasRoute._addFileChildren(AuthenticatedTrilhasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRouteWithChildren
  AuthenticatedBibliaRoute: typeof AuthenticatedBibliaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDevocionalRoute: typeof AuthenticatedDevocionalRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedEscolaRoute: typeof AuthenticatedEscolaRouteWithChildren
  AuthenticatedEstudosRoute: typeof AuthenticatedEstudosRouteWithChildren
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRouteWithChildren
  AuthenticatedTrilhasRoute: typeof AuthenticatedTrilhasRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRouteWithChildren,
  AuthenticatedBibliaRoute: AuthenticatedBibliaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDevocionalRoute: AuthenticatedDevocionalRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedEscolaRoute: AuthenticatedEscolaRouteWithChildren,
  AuthenticatedEstudosRoute: AuthenticatedEstudosRouteWithChildren,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRouteWithChildren,
  AuthenticatedTrilhasRoute: AuthenticatedTrilhasRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
