/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedBibliaRouteImport } from './routes/_authenticated/biblia'
import { Route as AuthenticatedDevocionalRouteImport } from './routes/_authenticated/devocional'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedEstudosRouteImport } from './routes/_authenticated/estudos'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAssistenteIndexRouteImport } from './routes/_authenticated/assistente.index'
import { Route as AuthenticatedAssistenteThreadIdRouteImport } from './routes/_authenticated/assistente.$threadId'
import { Route as AuthenticatedEstudosIndexRouteImport } from './routes/_authenticated/estudos.index'
import { Route as AuthenticatedPlanosIndexRouteImport } from './routes/_authenticated/planos.index'
import { Route as AuthenticatedPlanosSlugRouteImport } from './routes/_authenticated/planos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliaRoute = AuthenticatedBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevocionalRoute = AuthenticatedDevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudosRoute = AuthenticatedEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistenteIndexRoute =
  AuthenticatedAssistenteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistenteRoute,
  } as any)
const AuthenticatedAssistenteThreadIdRoute =
  AuthenticatedAssistenteThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistenteRoute,
  } as any)
const AuthenticatedEstudosIndexRoute =
  AuthenticatedEstudosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstudosRoute,
  } as any)
const AuthenticatedPlanosIndexRoute =
  AuthenticatedPlanosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlanosRoute,
  } as any)
const AuthenticatedPlanosSlugRoute = AuthenticatedPlanosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedPlanosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistente': typeof AuthenticatedAssistenteRouteWithChildren
  '/biblia': typeof AuthenticatedBibliaRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/estudos': typeof AuthenticatedEstudosRouteWithChildren
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/planos': typeof AuthenticatedPlanosRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/planos/': typeof AuthenticatedPlanosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/api/chat': typeof ApiChatRoute
  '/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/assistente': typeof AuthenticatedAssistenteIndexRoute
  '/estudos': typeof AuthenticatedEstudosIndexRoute
  '/planos': typeof AuthenticatedPlanosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRouteWithChildren
  '/_authenticated/biblia': typeof AuthenticatedBibliaRoute
  '/_authenticated/devocional': typeof AuthenticatedDevocionalRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/estudos': typeof AuthenticatedEstudosRouteWithChildren
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/assistente/$threadId': typeof AuthenticatedAssistenteThreadIdRoute
  '/_authenticated/planos/$slug': typeof AuthenticatedPlanosSlugRoute
  '/_authenticated/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/_authenticated/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/_authenticated/planos/': typeof AuthenticatedPlanosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistente'
    | '/biblia'
    | '/devocional'
    | '/diario'
    | '/estudos'
    | '/favoritos'
    | '/inicio'
    | '/metas'
    | '/pesquisa'
    | '/planos'
    | '/api/chat'
    | '/assistente/$threadId'
    | '/planos/$slug'
    | '/assistente/'
    | '/estudos/'
    | '/planos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblia'
    | '/devocional'
    | '/diario'
    | '/favoritos'
    | '/inicio'
    | '/metas'
    | '/pesquisa'
    | '/api/chat'
    | '/assistente/$threadId'
    | '/planos/$slug'
    | '/assistente'
    | '/estudos'
    | '/planos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistente'
    | '/_authenticated/biblia'
    | '/_authenticated/devocional'
    | '/_authenticated/diario'
    | '/_authenticated/estudos'
    | '/_authenticated/favoritos'
    | '/_authenticated/inicio'
    | '/_authenticated/metas'
    | '/_authenticated/pesquisa'
    | '/_authenticated/planos'
    | '/api/chat'
    | '/_authenticated/assistente/$threadId'
    | '/_authenticated/planos/$slug'
    | '/_authenticated/assistente/'
    | '/_authenticated/estudos/'
    | '/_authenticated/planos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia': {
      id: '/_authenticated/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof AuthenticatedBibliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devocional': {
      id: '/_authenticated/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof AuthenticatedDevocionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos': {
      id: '/_authenticated/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AuthenticatedEstudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistente/': {
      id: '/_authenticated/assistente/'
      path: '/'
      fullPath: '/assistente/'
      preLoaderRoute: typeof AuthenticatedAssistenteIndexRouteImport
      parentRoute: typeof AuthenticatedAssistenteRoute
    }
    '/_authenticated/assistente/$threadId': {
      id: '/_authenticated/assistente/$threadId'
      path: '/$threadId'
      fullPath: '/assistente/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistenteThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistenteRoute
    }
    '/_authenticated/estudos/': {
      id: '/_authenticated/estudos/'
      path: '/'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AuthenticatedEstudosIndexRouteImport
      parentRoute: typeof AuthenticatedEstudosRoute
    }
    '/_authenticated/planos/': {
      id: '/_authenticated/planos/'
      path: '/'
      fullPath: '/planos/'
      preLoaderRoute: typeof AuthenticatedPlanosIndexRouteImport
      parentRoute: typeof AuthenticatedPlanosRoute
    }
    '/_authenticated/planos/$slug': {
      id: '/_authenticated/planos/$slug'
      path: '/$slug'
      fullPath: '/planos/$slug'
      preLoaderRoute: typeof AuthenticatedPlanosSlugRouteImport
      parentRoute: typeof AuthenticatedPlanosRoute
    }
  }
}

interface AuthenticatedAssistenteRouteChildren {
  AuthenticatedAssistenteThreadIdRoute: typeof AuthenticatedAssistenteThreadIdRoute
  AuthenticatedAssistenteIndexRoute: typeof AuthenticatedAssistenteIndexRoute
}

const AuthenticatedAssistenteRouteChildren: AuthenticatedAssistenteRouteChildren =
  {
    AuthenticatedAssistenteThreadIdRoute: AuthenticatedAssistenteThreadIdRoute,
    AuthenticatedAssistenteIndexRoute: AuthenticatedAssistenteIndexRoute,
  }

const AuthenticatedAssistenteRouteWithChildren =
  AuthenticatedAssistenteRoute._addFileChildren(
    AuthenticatedAssistenteRouteChildren,
  )

interface AuthenticatedEstudosRouteChildren {
  AuthenticatedEstudosIndexRoute: typeof AuthenticatedEstudosIndexRoute
}

const AuthenticatedEstudosRouteChildren: AuthenticatedEstudosRouteChildren = {
  AuthenticatedEstudosIndexRoute: AuthenticatedEstudosIndexRoute,
}

const AuthenticatedEstudosRouteWithChildren =
  AuthenticatedEstudosRoute._addFileChildren(AuthenticatedEstudosRouteChildren)

interface AuthenticatedPlanosRouteChildren {
  AuthenticatedPlanosSlugRoute: typeof AuthenticatedPlanosSlugRoute
  AuthenticatedPlanosIndexRoute: typeof AuthenticatedPlanosIndexRoute
}

const AuthenticatedPlanosRouteChildren: AuthenticatedPlanosRouteChildren = {
  AuthenticatedPlanosSlugRoute: AuthenticatedPlanosSlugRoute,
  AuthenticatedPlanosIndexRoute: AuthenticatedPlanosIndexRoute,
}

const AuthenticatedPlanosRouteWithChildren =
  AuthenticatedPlanosRoute._addFileChildren(AuthenticatedPlanosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRouteWithChildren
  AuthenticatedBibliaRoute: typeof AuthenticatedBibliaRoute
  AuthenticatedDevocionalRoute: typeof AuthenticatedDevocionalRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedEstudosRoute: typeof AuthenticatedEstudosRouteWithChildren
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRouteWithChildren,
  AuthenticatedBibliaRoute: AuthenticatedBibliaRoute,
  AuthenticatedDevocionalRoute: AuthenticatedDevocionalRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedEstudosRoute: AuthenticatedEstudosRouteWithChildren,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
